baseurl = "https://example.org"
title = "Jonas Berg SkÃ¥nÃ¸y"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[services]
[services.disqus]
disqusShortname = "jonasskanoy"

[markup.highlight]
style = "github-dark"

[params]
  author = "Jonas Berg SkÃ¥nÃ¸y"
  info = "Philosophy and Tech"
  description = "Jonas Berg SkÃ¥nÃ¸y's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/profile.jpg"

  faviconSVG = "images/profile.jpg"
  favicon_32 = "images/profile.jpg"
  favicon_16 = "images/profile.jpg"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
name = "RSS"
icon = "fa fa-rss-square fa-2x"
weight = 1
url = "https://www.jonasskanoy.xyz/posts/index.xml"
rel = "alternate"
type = "application/rss+xml"


# Menu links
[[menu.main]]
name = "About ğŸ‘¨"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog ğŸ“œ"
weight = 2
url = "posts/"

[[menu.main]]
name = "Tags ğŸ·ï¸"
weight = 3
url = "tags/"

[[menu.main]]
name = "Library ğŸ“š"
weight = 4
url = "library/"

[[menu.main]]
name = "Contact me ğŸ“"
weight = 5
url = "contact/"
